java.lang.NullPointerException: Cannot invoke \"za.co.mawa.bes.dto.user.UserDto.getPartner()\" because the return value of \"za.co.mawa.bes.service.UserService.getUserByName(String)\" is null